# Generated by Django 4.1.4 on 2023-05-24 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, default="@", max_length=50)),
                (
                    "card_number",
                    models.CharField(blank=True, default=14, max_length=50),
                ),
                (
                    "background_banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile"
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("business", models.CharField(max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email_address", models.EmailField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("tiktok", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("paypal", models.URLField(blank=True)),
                ("cashapp", models.URLField(blank=True)),
                ("snap", models.URLField(blank=True)),
                ("discord", models.URLField(blank=True)),
                ("twitch", models.URLField(blank=True)),
                ("spotify", models.URLField(blank=True)),
                ("apple_music", models.URLField(blank=True)),
                ("sound_cloud", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
