# Generated by Django 4.2.2 on 2023-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tapncard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='media/images/profile/defaultBizman_5lfB6OA.jpg', upload_to='images/site')),
                ('ad_picture1', models.ImageField(default='media/images/site/defaultBizman_5lfB6OA.jpg', upload_to='images/site')),
                ('ad_picture2', models.ImageField(default='media/images/site/defaultBizman_5lfB6OA.jpg', upload_to='images/site')),
                ('ad_picture3', models.ImageField(default='media/images/site/defaultBizman_5lfB6OA.jpg', upload_to='images/site')),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
