# Generated by Django 4.2.2 on 2023-06-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tapncard_delete_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapncard',
            name='default_picture',
            field=models.ImageField(default='media/images/site/defaultBizman_5lfB6OA.jpg', upload_to='images/site'),
        ),
    ]
