# Generated by Django 4.2.1 on 2023-05-30 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, default="@", max_length=50)),
                (
                    "card_number",
                    models.CharField(blank=True, default=14, max_length=50),
                ),
                (
                    "background_banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("--light", "Light"),
                            ("--white", "White"),
                            ("--dark", "Dark"),
                            ("--purple", "Purple"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile"
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("business", models.CharField(max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email_address", models.EmailField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("facebook", models.URLField(default="http://www.facebook.com/")),
                (
                    "instagram",
                    models.URLField(blank=True, default="http://www.instagram.com/"),
                ),
                (
                    "tiktok",
                    models.URLField(blank=True, default="http://www.tiktok.com/"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, default="http://www.twitter.com/"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, default="http://www.linkedin.com/"),
                ),
                (
                    "paypal",
                    models.URLField(blank=True, default="http://www.paypal.com/"),
                ),
                (
                    "cashapp",
                    models.URLField(blank=True, default="http://www.cashapp.com/"),
                ),
                (
                    "snap",
                    models.URLField(blank=True, default="http://www.snapchat.com/"),
                ),
                (
                    "discord",
                    models.URLField(blank=True, default="http://www.discord.com/"),
                ),
                (
                    "twitch",
                    models.URLField(blank=True, default="http://www.twitch.com/"),
                ),
                (
                    "spotify",
                    models.URLField(blank=True, default="http://www.spotify.com/"),
                ),
                (
                    "apple_music",
                    models.URLField(blank=True, default="http://www.applemusic.com/"),
                ),
                (
                    "sound_cloud",
                    models.URLField(blank=True, default="http://www.soundcloud.com/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
