# Generated by Django 3.2.19 on 2023-06-07 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='background_banner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_banner', models.ImageField(upload_to='images/profile')),
                ('profile_picture', models.ImageField(upload_to='images/profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='@', max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('about', models.CharField(blank=True, max_length=300)),
                ('facebook', models.URLField(default='http://www.facebook.com/')),
                ('instagram', models.URLField(blank=True, default='http://www.instagram.com/')),
                ('tiktok', models.URLField(blank=True, default='http://www.tiktok.com/')),
                ('twitter', models.URLField(blank=True, default='http://www.twitter.com/')),
                ('linkedin', models.URLField(blank=True, default='http://www.linkedin.com/')),
                ('paypal', models.URLField(blank=True, default='http://www.paypal.com/')),
                ('cashapp', models.URLField(blank=True, default='http://www.cashapp.com/')),
                ('snap', models.URLField(blank=True, default='http://www.snapchat.com/')),
                ('discord', models.URLField(blank=True, default='http://www.discord.com/')),
                ('twitch', models.URLField(blank=True, default='http://www.twitch.com/')),
                ('spotify', models.URLField(blank=True, default='http://www.spotify.com/')),
                ('apple_music', models.URLField(blank=True, default='http://www.applemusic.com/')),
                ('sound_cloud', models.URLField(blank=True, default='http://www.soundcloud.com/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
