# Generated by Django 3.2.19 on 2023-06-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230604_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_banner',
            field=models.ImageField(blank=True, default='images/media/TapNCard Default Profile Banner.png', null=True, upload_to='images/profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(default='images/media/TapNCard Default Profile Picture.png', null=True, upload_to='images/profile'),
        ),
    ]
