# Generated by Django 3.2.19 on 2023-06-07 02:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_rename_post_profilepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePost',
            new_name='Post',
        ),
    ]
