# Generated by Django 3.2.19 on 2023-06-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20230604_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
