# Generated by Django 3.2.19 on 2023-06-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_profilepost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, default='http://www.facebook.com/'),
        ),
    ]
