# Generated by Django 3.2.19 on 2023-06-05 02:06

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20230604_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='background_banner',
            field=models.ImageField(blank=True, default=members.models.get_default_cover_pic, null=True, upload_to='images/profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='card_number',
            field=models.CharField(blank=True, default='14', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(blank=True, default=members.models.get_default_profile_pic, null=True, upload_to='images/profile'),
        ),
    ]
