# Generated by Django 3.2.19 on 2023-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_profile_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='facebook',
            field=models.URLField(default='http://www.facebook.com/', null=True),
        ),
    ]
