# Generated by Django 3.2.19 on 2023-06-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_post_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='apple_music',
            field=models.URLField(blank=True, default='http://www.applemusic.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cashapp',
            field=models.URLField(blank=True, default='http://www.cashapp.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='discord',
            field=models.URLField(blank=True, default='http://www.discord.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='instagram',
            field=models.URLField(blank=True, default='http://www.instagram.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='linkedin',
            field=models.URLField(blank=True, default='http://www.linkedin.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paypal',
            field=models.URLField(blank=True, default='http://www.paypal.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='snap',
            field=models.URLField(blank=True, default='http://www.snapchat.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sound_cloud',
            field=models.URLField(blank=True, default='http://www.soundcloud.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='spotify',
            field=models.URLField(blank=True, default='http://www.spotify.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tiktok',
            field=models.URLField(blank=True, default='http://www.tiktok.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='twitch',
            field=models.URLField(blank=True, default='http://www.twitch.com/', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='twitter',
            field=models.URLField(blank=True, default='http://www.twitter.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='apple_music',
            field=models.URLField(blank=True, default='http://www.applemusic.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cashapp',
            field=models.URLField(blank=True, default='http://www.cashapp.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discord',
            field=models.URLField(blank=True, default='http://www.discord.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, default='http://www.instagram.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default='http://www.linkedin.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paypal',
            field=models.URLField(blank=True, default='http://www.paypal.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='snap',
            field=models.URLField(blank=True, default='http://www.snapchat.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sound_cloud',
            field=models.URLField(blank=True, default='http://www.soundcloud.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify',
            field=models.URLField(blank=True, default='http://www.spotify.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tiktok',
            field=models.URLField(blank=True, default='http://www.tiktok.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitch',
            field=models.URLField(blank=True, default='http://www.twitch.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, default='http://www.twitter.com/', null=True),
        ),
    ]
