# Generated by Django 3.2.19 on 2023-06-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20230607_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='background_banner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='background_banner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='background_banner',
            field=models.ImageField(default='media/images/profile/TapNCard_Default_Profile_Banner.png', upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='profile_picture',
            field=models.ImageField(default='media/images/profile/defaultBizman.jpg', upload_to='images/profile'),
        ),
    ]
