# Generated by Django 3.2.19 on 2023-06-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20230607_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='user',
        ),
    ]
