# Generated by Django 3.2.19 on 2023-06-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20230608_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_banner',
            field=models.ImageField(blank=True, upload_to='images/profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/profile'),
        ),
    ]
