# Generated by Django 3.2.19 on 2023-06-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20230608_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='default_background_banner',
            field=models.ImageField(blank=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='default_profile_picture',
            field=models.ImageField(blank=True, upload_to='images/profile'),
        ),
    ]
