# Generated by Django 3.2.19 on 2023-06-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20230608_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='username',
        ),
    ]
