# Generated by Django 3.2.19 on 2023-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_remove_postimage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='postimage',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/profile'),
        ),
    ]
