# Generated by Django 3.2.19 on 2023-06-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20230608_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
