# Generated by Django 3.2.19 on 2023-06-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_delete_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='media/images/profile/defaultBizman_5lfB6OA.jpg', null=True, upload_to='images/profile')),
                ('background_banner', models.ImageField(blank=True, default='media/images/profile/TapNCard_Default_Profile_Banner_zZkKI0A.png', null=True, upload_to='images/profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.post')),
            ],
        ),
    ]
