# Generated by Django 3.2.19 on 2023-06-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='default_background_banner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='default_profile_picture',
        ),
    ]
