# Generated by Django 3.2.19 on 2023-06-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20230608_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='user',
            new_name='username',
        ),
    ]
