# Generated by Django 3.2.19 on 2023-06-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_rename_user_postimage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_banner',
            field=models.ImageField(blank=True, default='media/images/profile/TapNCard_Default_Profile_Banner_zZkKI0A.png', null=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/images/profile/defaultBizman_5lfB6OA.jpg', null=True, upload_to='images/profile'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
