# Generated by Django 3.2.19 on 2023-06-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_auto_20230609_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_banner',
            field=models.ImageField(default='media/images/profile/TapNCard_Default_Profile_Banner_zZkKI0A.png', upload_to='images/profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(default='media/images/profile/defaultBizman_5lfB6OA.jpg', upload_to='images/profile'),
        ),
    ]
