# Generated by Django 3.2.19 on 2023-06-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20230609_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
