# Generated by Django 3.2.19 on 2023-06-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(blank=True, default='Some sample text about yourself and your company', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='business',
            field=models.CharField(default='Your Company Here', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='email_address',
            field=models.EmailField(blank=True, default='youremail@mail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_name',
            field=models.CharField(default='Your Name Here', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_title',
            field=models.CharField(blank=True, default='Your Company Title Here', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, default='626-555-1212', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, default='@usernamehere', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.URLField(blank=True, default='www.yourwebsite.com'),
        ),
    ]
