# Generated by Django 3.2.19 on 2023-06-09 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0030_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='business',
            field=models.CharField(default='Company Name Here', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='email_address',
            field=models.EmailField(blank=True, default='Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_name',
            field=models.CharField(default='Full Name Here', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_title',
            field=models.CharField(blank=True, default='Company Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, default='Phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, default='@', max_length=50),
        ),
    ]
