# Generated by Django 3.2.19 on 2023-06-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_auto_20230609_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='business',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
