# Generated by Django 3.2.19 on 2023-06-11 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0032_auto_20230609_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='@', max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(default='media/images/profile/defaultBizman_5lfB6OA.jpg', upload_to='images/profile')),
                ('business', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('about', models.CharField(blank=True, max_length=300)),
                ('background_banner', models.ImageField(default='media/images/profile/TapNCard_Default_Profile_Banner_zZkKI0A.png', upload_to='images/profile')),
                ('facebook', models.URLField(default='http://www.facebook.com/username')),
                ('instagram', models.URLField(blank=True, default='http://www.instagram.com/username')),
                ('tiktok', models.URLField(blank=True, default='http://www.tiktok.com/username')),
                ('twitter', models.URLField(blank=True, default='http://www.twitter.com/username')),
                ('linkedin', models.URLField(blank=True, default='http://www.linkedin.com/username')),
                ('paypal', models.URLField(blank=True, default='http://www.paypal.com/username')),
                ('cashapp', models.URLField(blank=True, default='http://www.cashapp.com/username')),
                ('snap', models.URLField(blank=True, default='http://www.snapchat.com/username')),
                ('discord', models.URLField(blank=True, default='http://www.discord.com/username')),
                ('twitch', models.URLField(blank=True, default='http://www.twitch.com/username')),
                ('spotify', models.URLField(blank=True, default='http://www.spotify.com/username')),
                ('apple_music', models.URLField(blank=True, default='http://www.applemusic.com/username')),
                ('sound_cloud', models.URLField(blank=True, default='http://www.soundcloud.com/username')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
