# Generated by Django 4.2.2 on 2023-06-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, default='Some sample text about yourself and your company', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cashapp',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default='http://www.'),
        ),
    ]
