# Generated by Django 4.2.2 on 2023-06-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_alter_profile_about_alter_profile_cashapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
