# Generated by Django 4.2.2 on 2023-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_alter_post_website_alter_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cashapp',
            field=models.URLField(blank=True, default='https://cash.app/username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cashapp',
            field=models.URLField(blank=True, default='https://cash.app/username'),
        ),
    ]
