# Generated by Django 4.2.2 on 2023-09-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_alter_post_cashapp_alter_profile_cashapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cashapp',
            field=models.URLField(blank=True, default='https://www.cash.app/username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cashapp',
            field=models.URLField(blank=True, default='https://www.cash.app/username'),
        ),
    ]
